### PR TITLE
Chore : my first contribution  🤙🏼 #477

### PR DESCRIPTION
**Pull request by imnotrafa**
## Description ✏️

- Returns a list of undergrad student emails who are not registered for a given event.
- Finds the event attendees and filters down those students who are not attending.

## Type of Change 🐞
- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by tomas-salgado** [comment]
Hey @imnotrafa, is this PR ready? No rush if not, just want to make sure we don't have this as a draft when it is ready for review

**Comment by imnotrafa** [comment]
Hello @tomas-salgado , yes! sorry I forgot to submit currently got caught with school work. will be submitting a PR on Tuesday if thats okay.

**Comment by tomas-salgado** [comment]
Yep no worries @imnotrafa, just wanted to check!

**Comment by imnotrafa** [comment]
@tomas-salgado  I created a differnet pull request thus I believe this one can be deleted.

**Pull request closed without merging**
