### PR TITLE
feat: combine `#birthdays` channel messages 🎂

### LINKED ISSUE #416: Combine `#birthdays` channel messages 🎂
### Description

Every day, the StackBot sends a notification to the `#birthdays` channel wishing a happy birthday to each ColorStack member whose birthday it is. Currently, there is a separate message being sent for each member. There are some downsides to this:
- If members want to wish a happy birthday to everyone, they have to reply/react separately to each thread.
- Some members get more reactions/replies than others.

A small improvement we can make is combining all birthdays into 1 message.

### Acceptance Criteria

Here are examples of how the birthday message should look now:
- > We have `1` ColorStack birthday today -- everyone wish a happy birthday to `<@SLACK_USER_ID>`!
- > We have `2` ColorStack birthdays today -- everyone wish a happy birthday to `<@SLACK_USER_ID_1>` and `<@SLACK_USER_ID_2>`!
- > We have `3` ColorStack birthdays today -- everyone wish a happy birthday to `<@SLACK_USER_ID_1>`, `<@SLACK_USER_ID_2>` and `<@SLACK_USER_ID_3>`!

### Additional Context

The birthday notifications get sent in the [`sendBirthdayNotification`](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/member/use-cases/send-birthday-notification.ts#L8) function. We'll simply need to emit only 1 `notification.slack.send` job instead of multiple, and update the `message` field.

### PR DESCRIPTION
**Pull request by JustinhSE**
## Description ✏️

Closes #416 

Merges all the bday messages into 1 msg/day in #birthdays 

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by JustinhSE** [comment]
Screenshot 2024-07-29 at 4 29 47 PM

I tested this in a TS playground to make sure the outputs are correct.

**Comment by tomas-salgado** [comment]
@JustinhSE It looks like the integration test is failing [here](https://github.com/colorstackorg/oyster/actions/runs/10151361887/job/28070458816?pr=419) because of formatting issues. Have you set up the VSCode extensions [here](https://github.com/colorstackorg/oyster/blob/main/CONTRIBUTING.md#editor-setup)? Specifically, ESLint and Prettier will be helpful because when those are set up, upon saving the file most formatting issues will be resolved

**Comment by JustinhSE** [comment]
Hey @tomas-salgado I do have prettier but don't have the eslint extension. I am currently away but will finish this next week!

**Review by ramiAbdou — APPROVED** [review]
@JustinhSE I ran Prettier for you and slightly simplified some logic - thanks for your work here! Let's see what the reception to this is. I think it'll be really positive! 👍

**Pull request merged**
