### PR TITLE
feat: blur company reviews for users w/o access 🚫

### LINKED ISSUE #314: Modal on Companies Page 📃
### Description
See #316 for project overview. Note that this issue is dependent on a function implemented in #313.

If a member does not yet have access to the Companies page, when they go to the Companies page there should be a modal that appears that specifies why they don’t have access to reviews yet. 

### Acceptance Criteria

Within the [loader function](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.companies.tsx#L48-L108) for the Companies page, use the function `hasReviewsAccess` (implemented in issue #313) to check if user has access. 

If user does not have access, a modal should appear with the title “Oops! You missed a step”, and the following description: “To view company reviews, you must first add a review of one of your experiences. You can do so here!”, where the word “here” links users to the member profile page at “/profile/work” where they can add a review. 

### Additional Context

Take a look through the codebase to see various examples and implementations of Modals!

### PR DESCRIPTION
**Pull request by rafa1510**
## Description ✏️

Closes #314 

Describe what this PR does.

- When user does not have access to reviews page (checked by utilizing `hasReviewsAccess` from #313), then show a modal to specify why they don't have access to reviews yet
- image

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).
- [x] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by ciaracade** [comment]
This looks great to me!

**Review by tomas-salgado — APPROVED** [review]
Great work @rafa1510! Tested this locally and it's working perfectly. @ramiAbdou will take a final look but this looks good to ship 🚀

**Review by ramiAbdou — APPROVED** [review]
Thank you for the work here, @rafa1510! 🔥 I tested it out and was super smooth! 

I initially wanted to restrict the companies page altogether but as I was playing around w/ it, I thought it might've been just a tad too restrictive. So I made an update that instead just blurs out the company review and adds a message there instead of blocking access to the company page altogether. This will allow them to still see who works at a company, etc. Here is an example:

Screenshot 2024-09-24 at 11 35 00 AM

Thanks again to you and @ciaracade for collaborating on this feature! 🙂

cc: @tomas-salgado on the change!

**Comment by ciaracade** [comment]
@ramiAbdou Ateeeeeee. Nice working with you on this feature @rafa1510!

**Comment by rafa1510** [comment]
Likewise @ciaracade! 🤝🫡

**Pull request merged**
