### PR TITLE
docs: 'how to' testing w/ db 📝

### PR DESCRIPTION
**Pull request by wflore19**
## Description ✏️

- Clear step-by-step instructions for connecting to local database for testing (CLI/GUI).
- Troubleshooting tips for common connection issues.

## Type of Change 🐞

- [ ] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [x] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [x] I have manually tested my code (if applicable).
- [x] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by wflore19** [comment]
@ramiAbdou I've been using pgadmin app for db management, which is included in this doc, but installing it is an extra step. I've added it as a container to `docker-compose.yml` in this [branch](https://github.com/colorstackorg/oyster/compare/main...wflore19:oyster:wflore19/pgadmin-docker). It works out of the box on `yarn dx:up`.

image

**Comment by ramiAbdou** [comment]
> @ramiAbdou I've been using pgadmin app for db management, which is included in this doc, but installing it is an extra step. I've added it as a container to `docker-compose.yml` in this [branch](https://github.com/colorstackorg/oyster/compare/main...wflore19:oyster:wflore19/pgadmin-docker). It works out of the box on `yarn dx:up`.
> 
> image

I love the idea of having the GUI automatically spun up through Docker Compose! I'm personally not the biggest fan of the pgAdmin UI, but I'm okay with shipping it. Maybe if we find a dockerized version of some other GUI that's a bit more modern (ie: [Prisma Studio](https://www.prisma.io/studio)) we can migrate in the future.

Can you include those changes in this PR and update the documentation accordingly?

**Comment by wflore19** [comment]
Gonna look up how to use prisma

**Comment by wflore19** [comment]
Researched prisma studio, I got it containerized couldn't get it to connect to the db server. However installing prisma studio locally works like a charm, I like how beginner friendly the UI is. I got Pgadmin working already on `yarn dx:up` or I could implement prisma studio locally as a dev dep. Your call @ramiAbdou

**Pull request closed without merging**
