### PR TITLE
feat: edit a file resource's attachment

### LINKED ISSUE #262: Ability to edit a resource's attachment 🔗
### Description

Currently, a member can post a resource with an attachment, but can't edit the attachment after. This issue should introduce the ability to do so.

### Acceptance Criteria

When a member (who posted a file-based resource) clicks edit, it should show the attachment field. They should be able to see the already uploaded file, and they should also be able to upload a different file. If they choose a different file, then any previous files should be deleted both in the database and from cloud storage.

### Additional Context

Here is the [`ResourceAttachmentField`](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/shared/components/resource-form.tsx#L52), which controls the file input.

### PR DESCRIPTION
**Pull request by arelymartinez16**
## Description ✏️

Closes #262 

- Added the ResourceAttachmentField to the _profile.resources.$id_.edit.tsx file.
- Deleted attachment associated with the resource from the resourceAttachments table on the update-resource.ts file.

## Type of Change 🐞

- [X] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [X] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by tomas-salgado** [comment]
@arelymartinez16 it looks like there are quite a few extra files added to this PR that aren't relevant to the feature you are introducing. Would you be able to remove them along with the commented code that is not needed?

**Comment by arelymartinez16** [comment]
@tomas-salgado I can remove the comments without any problems. Just to clarify, do you want me to remove the CONTRIBUTORS.yml and package-lock.json files or is there anything else? I was confused why the CONTRIBUTORS.yml appeared in the PR if I already did a separate PR.

**Comment by tomas-salgado** [comment]
@arelymartinez16 You should remove `package-lock.json`, `turbo.json`, `yarn.lock`, and `CONTRIBUTERS.yml` from this PR. Not sure exactly why CONTRIBUTORS.yml is being added to your PR here, maybe you hadn't switch the branch from a previous PR?

**Comment by arelymartinez16** [comment]
Hi @tomas-salgado, I just removed the comments and the files. Let me know if there is anything else I should do.

**Comment by tomas-salgado** [comment]
@arelymartinez16 so it looks like you actually deleted these files entirely. If you go to the 'Files Changed' tab of this PR, we can see that those files would be completely removed from Oyster if we merged this PR, which isn't what we want. Rather, we just don't want to include any of the changes you had made to these files. 

I think the simplest approach to fix this now is to make a new branch. Specifically, you can follow these steps: 
1) go to the main branch with `git checkout main`, and get the latest changes of Oyster into your local repo using `git fetch upstream` and `git rebase upstream/main`
2) Create a new branch with a different name from this one
3) Copy and paste the specific changes relevant to this change in the necessary files, without making changes in the other files
4) From here, you should then be able to run `git add .`, `git commit -m <some message>`, `git push` and that should only add the necessary files to the PR. However the key thing is to note when you do `git add .`, check that only the files you want to include are being added. 


Git can be a bit tricky to work with sometimes, so let me know if you need any help!

**Comment by arelymartinez16** [comment]
@tomas-salgado I'm making changes to the right files and I am receiving an error on the last file I'm changing which is the update-resource.ts file. 

import { putObject } from '@oyster/infrastructure/object-storage';
Cannot find module '@oyster/infrastructure/object-storage' or its corresponding type declarations.

**Comment by arelymartinez16** [comment]
Would I have to import like this correct? @oyster/core/object-storage

**Comment by arelymartinez16** [comment]
@tomas-salgado I'm good now. Thanks for helping out, I'm about to put another PR from the new branch :)

**Comment by tomas-salgado** [comment]
Closing this since now we have PR here: https://github.com/colorstackorg/oyster/pull/386

**Pull request closed without merging**
