### PR TITLE
feat: store member directory profile urls on slack profile 👥

### LINKED ISSUE #497: Store Directory Profile URLs on Slack Profiles 🔗
### Description

We would like to be able to link each member's directory profile URL within their Slack profile. This will require implementing a function that retrieves all of the members with both Slack profiles and member directory profiles, and then passing in the member's directory URL as a new field in the Slack profiles. 

### Acceptance Criteria
- Retrieve all members with both Slack profiles (check `joined_slack_at` in `students` table) and member directory profiles (check `joined_member_directory_at` in `students` table)
- Generate the URL for each directory profile using the member ID 
- Store this URL into the Slack profile for each member
- Abide by any rate-limiting that Slack has (since this function will modify a large number of Slack profiles)

### Additional Context

We can see how the URL is generated for each directory profile [here](https://github.com/tomas-salgado/oyster/blob/1da5d3dc2035c29a94ab88c5d339966edb04c4cb/apps/member-profile/app/routes/_profile.directory.tsx#L464). Note that `generatePath` is a deterministic function, meaning that given a particular input (i.e. a member ID), the URL produced by this function will always be the same. 

Check the Slack documentation [here](https://api.slack.com/methods/users.profile.set). There is an example in the codebase of utilizing the Slack API to modify a Slack profile [here](https://github.com/tomas-salgado/oyster/blob/1da5d3dc2035c29a94ab88c5d339966edb04c4cb/packages/core/src/modules/slack/services/slack-user.service.ts#L31-L37). 

Don't worry about actually running this function-this will be done manually once the function is implemented!

### PR DESCRIPTION
**Pull request by savazques**
## Description ✏️

Closes #497 

Describe what this PR does.

- Returns a list of students who have both a member profile and slack profile
- For each student look up Slack profile by email, generate url, and set profile with newly added field
- After each update add delay to abide by Slack rate limits

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Review by tomas-salgado — APPROVED** [review]
Nice work @savazques! This was pretty solid, I just changed up the way we did rate limiting to use the RateLimiter function instead of a delay, and integrated environment variables to get the member directory base URL and the Slack field ID for the member directory URL. Rami will take a last look and then this should be good to ship! 🚀

**Comment by tomas-salgado** [comment]
Question for @ramiAbdou: I wonder if we should move this code into a separate file to be run as a script, since adding the member directory URL to Slack profiles is probably just a one-time thing. There's also various console logs printed as part of these functions that make sense when running a script but probably should be removed otherwise. Thoughts?

**Review by ramiAbdou — APPROVED** [review]
Great work, @savazques! I made an update so that when a new member joins a Slack workspace, it'll store their directory URL at that point (on top of the backfill script that you developed)!

**Comment by ramiAbdou** [comment]
> Question for @ramiAbdou: I wonder if we should move this code into a separate file to be run as a script, since adding the member directory URL to Slack profiles is probably just a one-time thing. There's also various console logs printed as part of these functions that make sense when running a script but probably should be removed otherwise. Thoughts?

Yeah I moved it to its own file but honestly we don't have a great way of running scripts currently so there's not much precedent set for that. I'm okay with the logs in the script function, but I removed the logs from the function that updates an individual profile (which is now used when a new members joins the Slack workspace)!

**Pull request merged**
