### PR TITLE
feat: send a shopify gift card using the admin dashboard 🎁

### LINKED ISSUE #185: Shopify API Integration - Gift Cards 🎁
### Description

When new members join ColorStack, they go through an "activation" process where if they complete a set of required steps, they will be able to claim a swag pack. Unfortunately, SwagUp, our swag pack provider, does not support sending certain items in our swag pack internationally (including Puerto Rico).

Obviously, we still want to reward these members for completing their activation process. What we've historically done is issue them a $50 gift card to our [merch store](https://colorstackmerch.org/), which is about the same value as our swag pack. The issue is that the process for issuing this gift card has been a bit tedious.

We want to implement an integration with Shopify (which powers our merch store), so that issuing a gift card is extremely easy to do within our Admin Dashboard. Luckily, Shopify has a [Gift Card API](https://shopify.dev/docs/api/admin-rest/2023-10/resources/gift-card) that should make this process easy.

### Acceptance Criteria

This issue should do the following:
- Implement the ability to create a gift card, using the Shopify API (ie: [`POST /gift_cards.json`](https://shopify.dev/docs/api/admin-rest/2023-10/resources/gift-card#post-gift-cards)).
  - Note: I haven't dug into the API documentation too much yet, but we _might_ have to create a Shopify "customer" first (ie: [`POST /customers.json`](https://shopify.dev/docs/api/admin-rest/2023-10/resources/customer#post-customers)) and use that customer ID in the gift card endpoint.
  - I would like to avoid introducing any new SDKs (ie: Shopify) to avoid potential bloating. Let's just use the native `fetch` API to build this integration.
- In the Admin Dashboard -> Students page, add an option when clicking on the row's option to "Send Gift Card". This should open a modal which contains a form asking for the "Amount".
- Upon submitting the form above, this should send the gift card to the member. This should also send an internal Slack notification.

Don't worry about testing this - just implement 90% and I'll jump in to help testing with a real Shopify API key.

### Additional Context

- [Here](https://github.com/colorstackorg/oyster/blob/main/apps/admin-dashboard/app/routes/_dashboard.students.tsx#L241) is the dropdown that controls the options available for a row in the students table in the Admin Dashboard.

### PR DESCRIPTION
**Pull request by Joyeleke**
## Description [WIP] ✏️

Closes #185 

In the Admin Dashboard -> Students Page, there is now a row option to "Send Gift Card".  On clicking the option, a modal opens with a form to take in the "Amount" to be sent. This sends a gift card to the member and also sends an internal slack notification.

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [ ] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by Joyeleke** [comment]
@ramiAbdou Finally got started on this issue. But here are my biggest questions?

1) Should I mainly write code for the happy path since I can't test certain error responses. My biggest question now is how should I handle some of these potential errors?

**Comment by Joyeleke** [comment]
@ramiAbdou just bumping this up because I believe you were out pitching last week

**Comment by ramiAbdou** [comment]
@Joyeleke it looks like this PR is closed, if it's still active feel free to reopen it and keep it in draft mode!

**Comment by ramiAbdou** [comment]
> Should I mainly write code for the happy path since I can't test certain error responses. My biggest question now is how should I handle some of these potential errors?

Great question, if there is an error, we should:
1. Display a generic error message like `Failed to create Shopify gift card.`.
2. Capture the error in Sentry using our `captureException` function in the `core` package!

**Pull request closed without merging**
