### PR TITLE
feat: levels.fyi to company pages 💸 

### PR DESCRIPTION
**Pull request by wflore19**
**re: [pull request #332](https://github.com/colorstackorg/oyster/pull/332)**

Closes [#320](https://github.com/colorstackorg/oyster/issues/320)

## Description ✏️  
- Added the Levels.fyi logo to the following [images](https://github.com/wflore19/oyster/tree/main/apps/member-profile/public/images) folder.
- Added Levels.fyi link to companies page.
- Implemented w/ Tooltip component.
- Added 'levels-fyi' to query function argument.

Screenshot 2024-06-30 at 6 27 14 AM

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Review by tomas-salgado — CHANGES_REQUESTED** [review]
Great work again @wflore19! Just one change with the way we implement the link, but otherwise this looks good to me

**Review by tomas-salgado — APPROVED** [review]
@ramiAbdou will give a final look when he's back, but LGTM! 🚀

**Comment by wflore19** [comment]
fixed the format issue in [PR #330](https://github.com/colorstackorg/oyster/pull/330#pullrequestreview-2134446860) while testing. Closes [#321](https://github.com/colorstackorg/oyster/issues/321)

**Review by ramiAbdou — APPROVED** [review]
Looks great, thanks @wflore19!

@tomas-salgado I know we talked about both options but I think the whitespace below the company logo that is created by putting the levels.fyi link in there looks a tad awkward, I think it looks a tad more natural next to the company name. I made that update, but let's see how this looks as we add more socials to each company and we can adjust if we feel differently!

Screenshot 2024-07-10 at 3 08 00 PM

**Pull request merged**
