### PR TITLE
feat: notify admins when a thread has 100 messages 🚨 

### LINKED ISSUE #535: Notify Internal Slack when a thread gets 100+ replies 😅
**Issue Reserved for Bloomberg Mentorship Program**

### Description

Sometimes things get a little hectic in the family slack..😅 In the case that a single Slack thread gets 100+ replies, we want the admins to get a notification so that they can monitor the thread in case it is getting out of hand. 

### Acceptance Criteria

- Implement a function within ‘packages/core/src/modules/slack/queries' that counts the number of replies a thread has (this will require counting how many times that particular `threadId` appears in the database)
- This function should also check if the number of messages in the thread is exactly 100, in which case the function should send a notification to the internal slack with a message implying that a particular thread is getting long
- This function should be called within the `addSlackMessage` function after adding a new message to the database

### Additional Context

We have a function `addSlackMessage`  that retrieves any new Slack message and adds it to the database (see [here](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/packages/core/src/modules/slack/use-cases/add-slack-message.ts#L10-L12)). Within this function, after adding the message to the database, we can trigger a new function that will count the number of replies in the given thread and notify the admins if there are exactly 100 messages in the thread. 

To notify the admins, we can utilize the job `notification.slack.send` similar to as used [here](https://github.com/colorstackorg/oyster/blob/main/packages/core/src/modules/swag-pack/use-cases/notify-swag-pack-inventory.ts#L10-L13). Note that all we have to do is put the workspace as ‘internal’ and add a message. Make sure to specify which thread is getting long.

### PR DESCRIPTION
**Pull request by ciaracade**
## Description ✏️

Closes #535 
- Implemented a function that counts the number of replies a thread has 
- Checks if the number of messages in the thread is exactly 100
- Sends a notification to the internal Slack with a message 

> 🚨 Uh-oh! Thread #0000000 has gone over 💯 replies!
    Better see what's going on. 👀

## Type of Change 🐞

- [X] Feature - A non-breaking change that adds functionality.

## Checklist ✅

- [X] I have done a self-review of my code.
- [X] I have manually tested my code (if applicable).
- [X] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Comment by ciaracade** [comment]
I am interested in any thoughts on this pull request. I understand what the original issue was asking for but I'm wondering if `notify-busy-slack-thread.ts` should have been split into two files: the 100-count query and a function located in `packages/core/src/modules/slack/usecases` that sends a message to the internal Slack.

**Comment by tomas-salgado** [comment]
> I am interested in any thoughts on this pull request. I understand what the original issue was asking for but I'm wondering if `notify-busy-slack-thread.ts` should have been split into two files: the 100-count query and a function located in `packages/core/src/modules/slack/usecases` that sends a message to the internal Slack and used in `add-slack-message.ts`

I think in this case it is fine as it is, because the logic is not too long so it's reasonable to have all of it together

**Review by tomas-salgado — APPROVED** [review]
LGTM @ciaracade! I just made a minor fix by changing the order of the imports to fix the lint error, but this looks good. Curious to see how often this ends up sending a message 😂

**Comment by ciaracade** [comment]
Awesome. This was so few lines I thought I was missing something. Glad to see it get approved soon : }

**Review by ramiAbdou — APPROVED** [review]
@ciaracade @tomas-salgado I modified this slightly to use the `reply_count` that comes from the Slack webhook when a reply is sent, this saves us from having to do a DB query every time a message gets sent in the Slack. See the docs [here](https://api.slack.com/events/message/message_replied)!

**Pull request merged**
