### PR TITLE
feat: updated dropdown component to use Radix's DropdownMenu

### PR DESCRIPTION
**Pull request by hebronmekuria**
## Description ✏️
The changes implemented make our DropDown item to return radix's dropdown component so that we can use those added functionalities. Currently, it doesn't fully work, because the trigger isn't correctly configured.
Related to #271 

## Type of Change 🐞

- [X] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [X] I have done a self-review of my code.
- [X] I have manually tested my code (if applicable).
- [X] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Review by ramiAbdou — COMMENTED** [review]
I'm doing a little bit of digging into the Radix library, and it doesn't seem like they have any components that fully support our use case - we're using a Combobox (ie: search bar + dropdown together) and the key aspect of that is the search bar. Ideally we want to have keyboard navigation so I'm in the search bar I can press the down key and it goes to the dropdown. Related issue in Radix [here](https://github.com/radix-ui/primitives/issues/1342).

Will have to think a little bit more on this one, it's really tricky!

**Comment by wflore19** [comment]
Can I help? @ramiAbdou

**Comment by ramiAbdou** [comment]
@wflore19 Yup that sounds good! Feel free to do exploration and share any learnings here with @hebronmekuria and I. One thing I'll just note is I want to be conservative with adding any new libraries, so if we can minimize the amount of external libraries we use to solve this, that'd be great. This is definitely one of the more difficult components to build properly, so I would just timebox yourself so that you don't spend too much time on it!

**Comment by wflore19** [comment]
## Update:

I've gotten the keyboard interactions working, I'm working on the 'create new tag' feature. I'm wondering if we need it. 

image

Leaving this feature up to the user could create problems, like duplicate tags, large number of tags only used by one resource, tags w/ typo errors.

duplicate tags

We could filter the current tags in the db and have general categories (Frontend, Backend, Infrastructure, Certificates, Career). If we need a new one it's small PR and merge. 

@ramiAbdou what do you think?

**Comment by wflore19** [comment]
I've visited this issue twice since I last commented but I can't solve it. I have the prototype [above](https://github.com/colorstackorg/oyster/pull/329#issuecomment-2271764004) using the Observer API, but the scroll functionality is buggy. This is the [feature branch](https://github.com/wflore19/oyster/tree/flo/search)

I've also looked into using the `dataset` element [here](https://stackoverflow.com/a/53827462) but failed to get it working for our use case (adding selected tags to a list for preview and creating a new tag if the tag doesn't exist).

**Pull request closed without merging**
