### PR TITLE
feat: split company page layout into multiple tabs 💼

### LINKED ISSUE #536: Update Companies page layout 📑
**Issue Reserved for Bloomberg Mentorship Program**

### Description

We want to improve the layout of the the page for each company with the ‘Companies’ tab (example: [Amazon’s page](https://app.colorstack.io/companies/hTVn7DlKCW1L9G0lN_z0N)). Right now, the structure of the page has all the Reviews first, and then if you scroll past all of them you can see the list of current employees and then finally the list of past employees as well. We want to improve the UX by having tabs for each of these sections. For now, we’ll have one tab for reviews, another tab for current employees, and a final tab for past employees

### Acceptance Criteria

- Modify the layout of each company page (see [here](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/routes/_profile.companies_.%24id.tsx)) to implement separate tabs for ‘Reviews’, ‘Current Employees’, and ‘Past Employees’

### Additional Context

Check out how we use and implement tabs for the [recap](https://app.colorstack.io/recap/2024-09-21/leaderboard) page [here](https://github.com/colorstackorg/oyster/blob/57032d5d9bfe81d49935aa6e2d9d213c0f6806e6/apps/member-profile/app/routes/_profile.recap.%24date.tsx#L156-L174). Note that this is using a custom `RecapNavigationItem` , but for our purposes it’s fine to use just a [NavigationItem](https://github.com/colorstackorg/oyster/blob/main/apps/member-profile/app/shared/components/navigation.tsx).

### PR DESCRIPTION
**Pull request by Wisesofthemall**
## Description ✏️

Closes #536 

Describe what this PR does.
Untitled Video October 1, 2024 1_33 AM

- Bullet points are helpful.
- Screenshots are helpful, if applicable.

## Type of Change 🐞

- [x] Feature - A non-breaking change which adds functionality.
- [ ] Fix - A non-breaking change which fixes an issue.
- [ ] Refactor - A change that neither fixes a bug nor adds a feature.
- [ ] Documentation - A change only to in-code or markdown documentation.
- [ ] Tests - A change that adds missing unit/integration tests.
- [ ] Chore - A change that is likely none of the above.

## Checklist ✅

- [x] I have done a self-review of my code.
- [ ] I have manually tested my code (if applicable).
- [ ] I have added/updated any relevant documentation (if applicable).

### CODE REVIEW

**Review by tomas-salgado — COMMENTED** [review]
@Wisesofthemall I'm curious to hear reasoning for why we should have each of the parts of this page (employees, reviews, etc.) into separate pages? My initial thought was that since there isn't really too much data it's fine to implement this issue by just making a change in a single file where we just only render whatever section is selected (so even if all the data is loaded, we only show a section of it at a time for ease of use). Just curious to hear if you considered this, and which approach you think might be better here!

**Comment by Wisesofthemall** [comment]
> @Wisesofthemall I'm curious to hear reasoning for why we should have each of the parts of this page (employees, reviews, etc.) into separate pages? My initial thought was that since there isn't really too much data it's fine to implement this issue by just making a change in a single file where we just only render whatever section is selected (so even if all the data is loaded, we only show a section of it at a time for ease of use). Just curious to hear if you considered this, and which approach you think might be better here!

Given the example listed (Recap page), that page uses separate pages to render specific pieces of data, so I was just following that logic. Additionally, with the use of separate pages, I'm utilizing Server-Side Rendering (SSR) as opposed to Client-Side Rendering (CSR), and here are the benefits:

Improved Performance: SSR can reduce the initial load time, especially for users on slower networks, as the content is pre-rendered on the server.

SEO Benefits: Pages rendered on the server are better optimized for search engines, which can improve the visibility of the content.

Scalability: As data grows, separating sections into different pages can help keep each page lightweight and maintain performance.

**Comment by Wisesofthemall** [comment]
But of course, I can refactor to Client Side Routing if its necessary

**Review by tomas-salgado — DISMISSED** [review]
Great work @Wisesofthemall! I've tested this all locally and it's working great. I initially had thought client-side rendering would be fine, but by implementing server-side rendering you are making it much easier for future developments on this page!

The one thing is that there are merge conflicts on one of the files, though I believe this is because of some new code that was added to that file during the big Opportunities feature Rami just built. We just need to make sure not to lose that code, and then this will be all good!

**Review by ramiAbdou — APPROVED** [review]
Great work here, @Wisesofthemall!

I made a couple of updates to bring this home:
1. Consolidate the past/current employees (that was my bad @tomas-salgado, I might've told you to separate those pages).
2. We'll automatically redirect to the employees page if there are no reviews. This is mainly to avoid showing empty information as much as possible (let me know if you disagree here).
3. Now that we're splitting the routes server-side, we'll no longer need to fetch all that information in the initial `/companies/:id` layout. So I removed those!

This is going to enable much more company-specific information development soon (ie: compensation data and more 👀👀)!

**Pull request merged**
